[package]
name = "macos-installer"
version = "1.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"